name: MPV Build Process
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Source Code
      - name: Checkout Source
        uses: actions/checkout@v1
      # Setup Java environment in order to build the Android app.
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      # Get the dependencies
      - name: Fetch The Dependencies
        run: cd buildscripts/ && bash download.sh
      # Build The Debug APK
      - name: Build APK
        run: cd buildscripts/ && bash buildall.sh
      # Create a Changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.2
        env:
          GITHUB_TOKEN: ${{ secrets.PANCAKE }}
      # Upload generated apk to the artifacts.
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "LICENSE,app/build/outputs/apk/debug/*.apk"
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.PANCAKE }}
      # Push generated apk to the telegram channel.
      - name: Push to Telegram Channel
        run: curl -F document=@"app/build/outputs/apk/debug/app-debug.apk" -F caption=${{steps.build_changelog.outputs.changelog}} "https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendDocument?chat_id=-1001363989926"
